#!/usr/bin/env python3

import re
from gradelib import *
from gradeutil_mp3_public import (
    _match_baseline_pagetable,
    _match_pagetable_with_faulted_page,
    _match_madvise_pagetable,
)

runner = Runner(save("xv6.out"))
# ======================================================================
#  Test Cases
# ======================================================================


@test(14, "Print Page Table (with read only page)")
def test_mp3_1():
    runner.run_qemu(shell_script(["mp3_1"]))
    runner.match("ugetpid_test starting")
    runner.match("ugetpid_test: OK")
    _match_baseline_pagetable(runner)


@test(14, "sbrk test", parent=test_mp3_1)
def test_mp3_2():
    runner.run_qemu(shell_script(["mp3_2"]))
    # Before faulting, the page table is in its baseline state.
    runner.match(r"^# Before sbrk\(PGSIZE \* 2\)")
    _match_baseline_pagetable(runner)
    runner.match(r"^# After sbrk\(PGSIZE \* 2\)")
    _match_baseline_pagetable(runner)
    runner.match(r"^# After sbrk\(-PGSIZE \* 2\)")
    _match_baseline_pagetable(runner)
    runner.match(r"^# After sbrk\(PGSIZE \* 2\) again")
    _match_baseline_pagetable(runner)

    # After faulting, the page table has one extra page.
    runner.match(r"^# After page fault at 0x0000000000005000")
    _match_pagetable_with_faulted_page(runner)

    # After deallocation, it returns to the baseline state.
    runner.match(r"^# After sbrk\(-PGSIZE \* 2\) again")
    _match_baseline_pagetable(runner)


@test(14, "madvise test", parent=test_mp3_2)
def test_mp3_3():
    runner.run_qemu(shell_script(["mp3_3"]))
    # --- Stage 1: Before madvise ---
    runner.match(r"^# Before madvise\(\)")
    _match_pagetable_with_faulted_page(runner)

    # --- Stage 2: After madvise ---
    runner.match(r"^# After madvise\(\)")
    _match_madvise_pagetable(runner)


@test(0, "report")
def test_report():
    # just a simple sanity check, will be graded manually
    check_answers("mp3-report.md")


@test(0, "bonus")
def test_bonus():
    # just a simple sanity check, will be graded manually
    check_answers("grade-mp3-bonus")


# ======================================================================
#  Run All Tests
# ======================================================================

run_tests()
